draw_config:
  n_columns: 2
  draw_key_sides: true
  append_colon_to_layer_header: true
  small_pad: 4.0
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 1.0
  inner_pad_h: 1.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: true
  key_side_pars:
    rel_x: 0
    rel_y: 0
    rel_w: 12
    rel_h: 12
    rx: 8
    ry: 8
  svg_extra_style: |
    svg.keymap {
      background-color: #434343 !important;
      font-family: Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 14px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
    }
    .key rect {
      # fill: #D3FF89 !important;      /* キーの色 */
      # stroke: #B3DF69 !important;    /* 枠線の色 */
      fill: #333333 !important;      /* キーの色 */
      stroke: #000000 !important;    /* 枠線の色 */
      stroke-width: 2px;
    }
    .key text {
      fill: #FFFFFF;
    }
    text { fill: #000000; }
    .key:has(use[href^="#trackball_"]) text.hold {
      fill: #FFFFFF !important;
      font-size: 12px !important;
      font-weight: bold !important;
      display: block !important;
      transform: translate(0px, -10px) !important;
    }
    .key:has(use[href="#rotaryencoder"]) text.hold {
      fill: #FFFFFF !important;
      font-size: 12px !important;
      font-weight: bold !important;
      display: block !important;
      transform: translate(0px, -20px) !important;
    }

  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 58
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs:
    trackball_14mm: |
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96">
        <defs>
          <radialGradient id="trackball-gradient" cx="50%" cy="50%" r="50%">
            <!-- <stop offset="0%" stop-color="#ffffff"/>
            <stop offset="100%" stop-color="#dddddd"/>-->
            <stop offset="0%" stop-color="#444444"/>
            <stop offset="100%" stop-color="#222222"/>
          </radialGradient>
        </defs>
        <rect x="2" y="2" width="92" height="92" fill="#ffffff" stroke="#000000"/>
        <ellipse cx="48" cy="48" rx="36" ry="36" fill="url(#trackball-gradient)" stroke="#000000"/>
      </svg>
    trackball_19mm: |
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96">
        <defs>
          <radialGradient id="trackball-gradient" cx="50%" cy="50%" r="50%">
            <!-- <stop offset="0%" stop-color="#ffffff"/>
            <stop offset="100%" stop-color="#dddddd"/> -->
            <stop offset="0%" stop-color="#444444"/>
            <stop offset="100%" stop-color="#222222"/>
          </radialGradient>
        </defs>
        <rect x="2" y="2" width="92" height="92" fill="#ffffff" stroke="#000000"/>
        <ellipse cx="48" cy="48" rx="46" ry="46" fill="url(#trackball-gradient)" stroke="#000000" stroke-width="3.5" />
      </svg>
    rotaryencoder: |
      <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="39 0 102 101">
        <path 
          class="glyph"
          style="fill: #333333 !important; fill-opacity: 1 !important;"
          fill="#FFFFFF" 
          stroke="#000000" 
          stroke-width="3.5" 
          stroke-linejoin="round"
          d="M 83.31 100 C 79.56 99.35 75.85 98.52 72.35 97.1 L 72.56 88.87 C 69.96 87.87 67.37 86.41 64.78 84.3 L 57.49 88.6 C 54.91 85.98 52.35 83.41 49.78 80.2 L 54.52 73.16 C 53 71.2 51.28 68.21 50.32 64.98 L 42.05 64.92 C 41.18 61.6 40.44 57.96 40 53.54 L 47.68 50.53 C 47.52 47.76 47.94 43.87 48.48 41.09 L 41.83 36.52 C 42.95 32.98 44.26 29.48 46.14 26.11 L 54.26 27.65 C 55.63 25.03 57.68 22.59 60.07 20.24 L 56.81 12.84 C 59.49 10.3 62.69 8.11 66.13 6.08 L 72.2 11.7 C 75.13 10.26 78.51 9.3 80.99 9.01 L 82.33 0.71 C 86.2 0.05 90.28 0 93.77 0.37 L 95.67 8.15 C 98.67 8.63 101.69 9.31 104.78 10.47 L 110.3 4.51 C 113.73 6.03 117.06 8.07 119.99 10.26 L 117.56 17.89 C 120 20.29 122.39 22.63 123.72 24.88 L 131.77 22.84 C 133.9 26.1 135.55 29.45 136.83 32.88 L 130.54 37.98 C 131.43 41.1 131.95 44.6 132.12 47.33 L 140 49.78 C 139.84 53.58 139.53 58.28 138.77 61.02 L 130.52 62.02 C 129.72 65.21 128.52 68.02 127.12 70.61 L 132.29 77.06 C 130.69 79.64 128.05 83.07 125.22 85.83 L 117.84 82.11 C 115.98 83.93 113.32 85.89 110.29 87.25 L 111.07 95.64 C 107.89 97.18 104.33 98.39 100.47 99.34 L 96.28 92.1 C 93.74 92.59 89.75 92.88 86.94 92.45 Z" />
      </svg>

parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {}
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    UP: '▲'
    DOWN: '▼'
    LEFT: '◀'
    RIGHT: '▶'
    TAB: '↹'
    RGUI: '⌘'
    LGUI: '⌘'
    BSPC: '⌫'
    # RET: '⏎'
    RET: '↵'
    LSHFT: '⇧'
    RSHFT: '⇧'
    ESC: '⎋'
    LALT: '⌥'
    RALT: '⌥'
    LCTRL: '^'
    RCTRL: '^'
    SPACE: '␣'
    OTHER1: '◇'
    OTHER2: '○'
    OTHER3: '▢'
    OTHER4: '🛆'
    OTHER5: '×'
    

  zmk_combos: {}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
  # ----- Raw bindings for encoders/trackball -----
  raw_binding_map:
    '&TB1_mouse':  { tap: '$$trackball_19mm$$', hold: 'Mouse' }
    '&TB1_scroll':  { tap: '$$trackball_19mm$$', hold: 'Scroll' }
    '&TB2_mouse':  { tap: '$$trackball_14mm$$', hold: 'Mouse' }
    '&TB2_scroll':  { tap: '$$trackball_14mm$$', hold: 'Scroll' }
    '&RE_scroll_ud':  { tap: '$$rotaryencoder$$', hold: '↑↓' }
    '&RE_scroll_lr':  { tap: '$$rotaryencoder$$', hold: '←→' }
    